slam_toolbox:
  ros__parameters:

    # --- 1. CONFIGURATION DU SOLVEUR (HAUTE PRÉCISION) ---
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # --- 2. FRAMES & TOPICS ACKERMANN ---
    odom_frame: odom
    map_frame: map
    base_frame: ldlidar_base         # <-- Aligné sur ton launch actuel
    scan_topic: /scan                # <-- Laisse /scan, le launchfile gère le remapping
    use_map_saver: true
    mode: mapping 

    # --- 3. TIMING & RENDER (REPRIS DE TON ANCIEN ROBOT PROPRE) ---
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 1.0         # Cartographie ultra-réactive (1s)
    resolution: 0.05                 # Résolution fine de 5cm
    max_laser_range: 12.0            # <-- Coupe les points lointains bruités (Le secret de ta carte propre !)
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # --- 4. GESTION DU MOUVEMENT (FORCÉ POUR FAKE ODOM) ---
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.0     # <--- CORRECTION : Force le calcul même si l'odom statique dit 0
    minimum_travel_heading: 0.0      # <--- CORRECTION : Force le calcul même sans rotation odométrique
    
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # --- 5. FERMETURE DE BOUCLE ---
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # --- 6. PÉNALITÉS ---
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0

    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    min_pass_through: 2
    occupancy_threshold: 0.1